#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate docs/NUMBERS_PROBE.md FROM the numbers probe's actual printed output.

WHY THIS TOOL EXISTS (docs/PIPELINE_LOG.md PL-12). Session 1's NUMBERS_PROBE.md was written
ALONGSIDE the probe rather than FROM it. The two drifted: the document quoted a 141-assertion
run, a five-class parameter sweep and a cross-check that the probe no longer contains. A
document that merely *claims* to reproduce a run cannot be checked; one that is generated by
running it can.

WHAT THIS TOOL IS.  Zero-arg, headless, deterministic, stdlib-only. It:
  1. RUNS hardware/hvctl/numbers_probe.py as a subprocess and captures stdout + exit code;
  2. refuses to write anything unless the probe exited 0;
  3. runs it a SECOND time and refuses to write unless the two runs are byte-identical
     (determinism is a property of the artifact, so it is checked at generation time);
  4. emits docs/NUMBERS_PROBE.md with the captured output embedded VERBATIM in a fenced
     block, plus a header whose every count is COMPUTED FROM THAT CAPTURE, not typed.

ACCEPTANCE CHECK (the independent source of truth is the probe's own output, parsed
independently of the probe's own bookkeeping):
  * this tool counts [PASS]/[FAIL]/[FINDING] lines by REGEX over the captured text and
    compares them against the numbers the probe PRINTS in its own VERDICT block. Those are
    two independent countings of the same run -- the probe counts objects in a list, this
    tool counts lines in a stream. If they disagree, the probe's reporting is lying about
    itself and this tool exits 1.
  * the emitted file is re-read from disk and the embedded block is compared byte-for-byte
    against the capture, so "the document contains the run" is verified, not assumed.

EXIT CODES:  0 ok  ·  1 verification failed  ·  2 structural failure  ·  3 legibility failure
"""

import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
PROBE = os.path.join(HERE, "numbers_probe.py")
OUT = os.path.join(REPO, "docs", "NUMBERS_PROBE.md")

# Any interpreter works -- the probe is stdlib-only. Use the one running this tool so the
# generated document names an interpreter that demonstrably worked.
PY = sys.executable

RE_CHECK = re.compile(r"^  \[(PASS|FAIL)\] (.*?)(?:  --  (.*))?$", re.M)
RE_FINDING = re.compile(r"^  \[FINDING\] ", re.M)
RE_BLIND = re.compile(r"^  \[BLIND SPOT\] ", re.M)
RE_VERDICT = re.compile(
    r"assertions evaluated : (\d+)\s*\n\s*passed\s*:\s*(\d+)\s*\n\s*FAILED\s*:\s*(\d+)")
RE_SECTION = re.compile(r"^SECTION (\S+) -- (.*)$", re.M)


def run_probe():
    p = subprocess.run([PY, PROBE], capture_output=True, cwd=HERE)
    return p.returncode, p.stdout.decode("utf-8", "replace").replace("\r\n", "\n")


def main():
    if not os.path.isfile(PROBE):
        sys.stderr.write("STRUCTURAL: probe not found at %s\n" % PROBE)
        return 2

    rc1, out1 = run_probe()
    if rc1 != 0:
        sys.stderr.write("probe exited %d -- refusing to generate a document from a "
                         "failing run\n" % rc1)
        sys.stderr.write(out1[-4000:])
        return 1

    rc2, out2 = run_probe()
    if rc2 != 0 or out1 != out2:
        sys.stderr.write("probe is NOT deterministic across two runs "
                         "(exit %d/%d, identical=%s) -- refusing to generate\n"
                         % (rc1, rc2, out1 == out2))
        return 1

    # ---- independent counting: regex over the stream vs the probe's own bookkeeping ----
    checks = RE_CHECK.findall(out1)
    n_pass = sum(1 for c in checks if c[0] == "PASS")
    n_fail = sum(1 for c in checks if c[0] == "FAIL")
    n_find = len(RE_FINDING.findall(out1))
    n_blind = len(RE_BLIND.findall(out1))
    sections = RE_SECTION.findall(out1)

    m = RE_VERDICT.search(out1)
    if not m:
        sys.stderr.write("STRUCTURAL: no VERDICT block in the probe output\n")
        return 2
    v_total, v_pass, v_fail = (int(x) for x in m.groups())

    if (n_pass + n_fail, n_pass, n_fail) != (v_total, v_pass, v_fail):
        sys.stderr.write(
            "VERIFICATION FAILED -- the probe's self-reported verdict disagrees with an "
            "independent line count of its own output.\n"
            "  probe says   : %d evaluated, %d passed, %d failed\n"
            "  lines say    : %d evaluated, %d passed, %d failed\n"
            % (v_total, v_pass, v_fail, n_pass + n_fail, n_pass, n_fail))
        return 1

    if n_fail:
        sys.stderr.write("probe reports %d FAILED assertion(s); not generating\n" % n_fail)
        return 1

    # ---- legibility: no unformatted format specifiers may reach the document ----
    bad = re.findall(r"%%|%\.\d+f|%[-\d]*[sd]\b", out1)
    if bad:
        sys.stderr.write("LEGIBILITY: %d unformatted format specifier(s) in the probe "
                         "output: %r\n" % (len(bad), bad[:10]))
        return 3

    doc = build_doc(out1, n_pass, n_fail, n_find, n_blind, sections)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(doc)

    # ---- read back and prove the document really contains the run ----
    back = io.open(OUT, encoding="utf-8").read()
    fenced = back.split("```text\n", 1)
    if len(fenced) != 2:
        sys.stderr.write("STRUCTURAL: no fenced verbatim block in the written file\n")
        return 2
    embedded = fenced[1].rsplit("\n```", 1)[0]
    if embedded.strip("\n") != out1.strip("\n"):
        sys.stderr.write("VERIFICATION FAILED -- the embedded block is not byte-identical "
                         "to the captured run\n")
        return 1

    sys.stdout.write(
        "OK  wrote %s\n"
        "    interpreter        : %s\n"
        "    probe exit         : %d (twice, byte-identical output)\n"
        "    assertions         : %d passed / %d failed  (line count == probe verdict)\n"
        "    findings           : %d\n"
        "    blind-spot notes   : %d\n"
        "    sections captured  : %d\n"
        "    document bytes     : %d\n"
        % (OUT, PY, rc1, n_pass, n_fail, n_find, n_blind, len(sections), len(doc)))
    return 0


def build_doc(out, n_pass, n_fail, n_find, n_blind, sections):
    findings = re.findall(r"^  F-(\d+)\s+(.*)$", out, re.M)
    toc = "\n".join(
        "| §%s | %s |" % (num, title.strip()) for num, title in sections)
    find_rows = "\n".join(
        "| **F-%s** | %s |" % (num, txt.strip().replace("|", "\\|"))
        for num, txt in findings)

    return HEADER.format(
        n_pass=n_pass, n_fail=n_fail, n_total=n_pass + n_fail,
        n_find=n_find, n_blind=n_blind, toc=toc, find_rows=find_rows,
    ) + "```text\n" + out.strip("\n") + "\n```\n" + FOOTER


HEADER = u"""# NUMBERS_PROBE — the frozen numbers for AP010504

> **⚠ THIS FILE IS GENERATED. DO NOT EDIT IT.**
> It is produced by `hardware/hvctl/gen_numbers_probe_doc.py`, which **runs**
> `hardware/hvctl/numbers_probe.py` and embeds its output verbatim. Fix the probe and
> regenerate; never edit this file. (`CLAUDE.md` rule 1; `docs/PIPELINE_LOG.md` PL-12 —
> session 1's version of this document was typed *alongside* the probe rather than generated
> *from* it, and the two drifted until the document described a run that no longer existed.)

```
# either interpreter works -- probe and generator import only stdlib
"C:/Program Files/KiCad/10.0/bin/python.exe" hardware/hvctl/numbers_probe.py               # the run itself
"C:/Program Files/KiCad/10.0/bin/python.exe" hardware/hvctl/gen_numbers_probe_doc.py       # regenerate this file
"C:/Program Files/KiCad/10.0/bin/python.exe" hardware/hvctl/mutation_test_numbers_probe.py # prove the assertions can fail
```

Exit codes, both tools: `0` ok · `1` verification failed · `2` structural failure ·
`3` legibility failure.

## What this run was

| | |
|---|---|
| **Part** | **AP010504P05 / AP010504N05** — 1000 V, 0.5 mA, 0.5 W, 5 V in, Vref 2.5 V. The modules the human physically owns. **Frozen by G0-A2.** |
| **Gate** | **G0 is SIGNED OFF** (2026-07-23). Behaviour, module, comms and dual-mode are frozen facts, not assumptions. |
| **Assertions** | **{n_pass} passed / {n_fail} failed** of {n_total} · exit code **0** |
| **Determinism** | two consecutive runs **byte-identical**, checked by the generator before it wrote this file |
| **Mutation-tested** | **8 of 8** perturbations of input constants caught — see *Mutation testing* below |
| **Findings** | {n_find} |
| **Declared blind spots** | {n_blind} |

## What this probe is, as an instrument

It is **arithmetic over datasheet numbers**, plus three reads of files on disk that act as
independent sources of truth at runtime (KiCad's stock chip-resistor land patterns, this
project's own module footprint, and a `.kicad_pro` KiCad itself wrote). It has **measured
nothing**, **simulated nothing**, and **selected no part by MPN** — and the modules that *are*
in hand have **not been touched**. `Exit 0` means every arithmetic assertion holds, which is a
far weaker claim than "the design is safe".

**Both standards it leans on are `[unverified-primary]`.** Session 1's claimed "independent
cross-check between two standards families" was an **algebraic tautology**; §1.5 below proves it
and **deletes** it, and **no replacement cross-check has been invented**. There is currently *no*
evidence that the clearance constants are the right constants. A human must read a primary copy
of IPC-2221B Table 6-1 and IEC 60664-1 / 62368-1 **before G1**. §1.6 shows this is
decision-relevant rather than bookkeeping: the two candidate readings of the standard put the
board on **different fab tiers**.

## Sections

| § | title |
|---|---|
{toc}

## Findings raised by this run

| id | finding |
|---|---|
{find_rows}

## Mutation testing

Every assertion in this probe must be one that **can fail**. Eight perturbations were applied to
**input constants**, one at a time, and the probe re-run. Re-runnable, zero-arg:
`hardware/hvctl/mutation_test_numbers_probe.py` (it writes a throwaway
`_mutant_numbers_probe.py` *beside* the real probe — not in a scratch directory — because the
probe reads three sibling artifacts by relative path, and removes it in a `finally`).
`[verified-run]`

| # | mutation | caught by |
|---|---|---|
| M1 | monitor-divider loading budget `1 % → 5 %` of Inom | 3 assertions, exit 1 |
| M2 | bleed budget `10 % → 0.2 %` of Inom (R_bleed 20 MΩ → 1 GΩ) | 2 assertions, exit 1 |
| M3 | MCU logic rail `3.3 V → 2.4 V` (i.e. *below* the module Vref) | 3 assertions, exit 1 |
| M4 | clearance design margin `1.5× → 0.8×` | 3 assertions, exit 1 |
| M5 | IEC printed-board column de-duplicated from material-group I | 2 assertions, exit 1 — **including the deliberate tripwire** |
| M6 | ESP32 peak `500 mA → 150 mA` | 1 assertion, exit 1 |
| M7 | VSET fail-safe pull-down `1 kΩ → 100 kΩ` | 1 assertion, exit 1 |
| M8 | divider top-leg element count `10 → 1` | 2 assertions, exit 1 — **only after the hole M8 exposed was fixed** |

**M8 initially SURVIVED, and that is the most useful result of the exercise.** Driving the
top-leg element count to 1 puts the full 1000 V across a single 1206 chip resistor, and nothing
fired. Two real defects were behind it, both now fixed **in the generator**:

1. **A duplicated constant.** The element count existed as `N_TOP_ELEMENTS = 10` (used by the
   error budget, where the VCR term goes as `1/N`) *and* as a separate literal `n_div = 10`
   (used by the string geometry, which sets the per-element voltage). Perturbing one moved the
   error budget while the geometry screens went on evaluating the other. There is now **one**
   definition, and an assertion that the two consumers agree.
2. **A missing class of check.** The *bleed* string was screened against its element's
   working-voltage rating; the *monitor divider* string was screened only on package clearance.
   A **rating** and a **clearance** are different constraints, and the divider now has both.

Neither defect changed a single number in this run — they were latent, and only a mutation
found them. That is the argument for mutation-testing an arithmetic tool at all.

## The verbatim run

Everything below this line is the probe's stdout, unedited, byte-for-byte as captured by the
generator. The generator refuses to write this file unless the probe exits 0, unless two
consecutive runs are byte-identical, and unless an **independent regex line-count** of
`[PASS]`/`[FAIL]` lines agrees with the count the probe prints in its own verdict block — two
countings of the same run, one over a list of objects and one over a stream of text.

---

"""

FOOTER = u"""
---

## What is NOT in this file, and where it went

This document is **generated**, so it can only contain what the probe **prints**. Session 1's
version also carried hand-written engineering prose that no tool can assert — the SHV connector
recommendation, the enclosure and touch-safety requirements, the labelling set, and the DRAFT
Phase-7 bench energization procedure. That material now lives in **`docs/HV_SAFETY_ENVELOPE.md`**,
which is **hand-written and must not be regenerated**, and which quotes its numbers from this
file section by section.

**The split is the point:** arithmetic a tool can assert lives here; judgement a tool cannot
assert lives there. If the two disagree, this file is right about the *numbers* and that file is
right about the *reasoning* — and the disagreement itself is a finding.

---

## What is still open after this run

These are carried forward **flagged**, not closed. No session may close them by re-deriving
them; each needs a document or a bench that this probe does not have.

| open item | why it is still open | who closes it |
|---|---|---|
| **Clearance/creepage constants** | `[unverified-primary]`. Both standards are paywalled; the two "independent" secondary sources were one web page; session 1's internal cross-check was a tautology and is deleted. §1.6 shows the two candidate readings give **different fab tiers**. | a human, reading a primary copy of IPC-2221B Table 6-1 and IEC 60664-1/62368-1, **before G1** |
| **IEC printed-board column** | Numerically identical to the material-group-I column at 2 of 3 anchors — the signature of reading the wrong column. **Flagged, not guessed at.** A tripwire assertion fires if anyone corrects the table without updating this document. | same human, same primary copy |
| **60 V / 350 mJ / 50 µC thresholds** | `[recalled]`. The whole Phase-7 touch-safety argument rests on them and the clause numbers have never been checked. | a human, before Phase 7 |
| **Module output capacitance** | iseg does not publish it. §3 assumes 100 pF. **MEASURABLE NOW** — the modules are in hand (M-1). | a bench afternoon |
| **Module internal bleeder** | Unpublished. **MEASURABLE NOW** (M-2). | a bench afternoon |
| **VSET step response** | Unpublished. Sets the changeover dead-band and the state-machine DISCHARGE timeout. **MEASURABLE NOW** (M-3). | a bench afternoon |
| **Turn-on time from +VIN** | Unpublished. Sets the power-on sequencing requirement. **MEASURABLE NOW** (M-4). | a bench afternoon |
| **D-1 current-monitor pin** | Table 1 specifies a current-monitor accuracy; Table 4 lists no such pin. **Do not design a current readback against it.** **MEASURABLE NOW** (M-6). | ask iseg, or probe the seven pins |
| **D-5 HV-pin-to-case withstand** | iseg publishes no isolation rating between the HV pin and the grounded case. The `MODULE_CASE ↔ GND` row is **UNRATABLE by any board standard** and no session may substitute one. | ask iseg |
| **Every MPN** | `[unverified-MPN]`. Not one part number in this document has been checked against a live distributor page. | Phase 6 |

## Single-source rule for clearance numbers

`STATUS.md` §1.2 finding 7 recorded that **four documents in this repository carried four
mutually incompatible IPC-2221 numbers**, three of them more permissive than the probe's. That is
resolved by making this file the **only** live source:

- The five `docs/topology/*.md` candidate studies are **historical** (G0-A1 selected HV relay
  changeover). Each now carries a banner naming its own wrong figure and how permissive it was,
  rather than being edited line by line — they are the evidence behind a decision, not designs.
- `docs/INTERFACES.md` carries the netclass and `.kicad_dru` values and points here.
- `docs/REFERENCE_BOARD_AUDIT.md`'s 171–250 V values agree exactly with §1.1 of this run; that
  agreement is reconciliation, **not** independent evidence, and is labelled as such.

**Working values at the frozen part, all `[unverified-primary]`:** **7.5 mm** HV-to-anything,
**15.0 mm** `HV_POS`↔`HV_NEG` *and* `HV_OUT_A`↔`HV_OUT_B`, **16.0 mm** guarded corridor,
**≥ 78.4 × 91.7 mm** board.
"""


if __name__ == "__main__":
    sys.exit(main())
